Change docker hub repository and update README
arfc/cyclus_blue_waters pull request #1
Opened 2017-06-01 20:48 UTC by adityapb

2017-06-01 21:20 UTC, katyhuff requested changes
This looks great! I left a few minor suggestions!

2017-06-01 21:20 UTC, katyhuff commented on README.rst
> +    |``--walltime``  |Wall time                      |
Let's make sure that this is a clear definition of the variable. "Wall time" is jargon. How about "max time your job can run, hours:minutes:seconds"

2017-06-01 21:20 UTC, katyhuff commented on README.rst
> +    |``--spec-file`` |Path of specification file     |
Define the specification file.

2017-06-01 21:20 UTC, katyhuff commented on README.rst
> +
Add some explanatory text here. Answer the question "when we might need to update the docker image in the future?"

2017-06-01 21:20 UTC, katyhuff commented on README.rst
Please add some explanatory text here. Specifically, set up an example use case. "Imagine you have a cyclus simulation that you would like to run many times with varied parameters or agents. You can use this workflow to generate an input file for each desired simulation and to run those input files simultaneously on the Blue Waters supercomputer."

2017-06-01 21:20 UTC, katyhuff commented on README.rst
> +3. Tag the image using the following command,
Let's say, "Tag, or label, this version of the docker image using the following command:"

2017-06-01 21:20 UTC, katyhuff commented on README.rst
> +        $ sudo docker tag <IMAGE_ID> arfc/cyclus_blue_waters:latest
Tell the user how to decide what to put in the <IMAGE_ID> place. Explain what is a good example IMAGE_ID .

2017-06-02 19:29 UTC, adityapb commented on README.rst
> +3. Tag the image using the following command,
Now that we have the automated build set up, this won't be necessary

2017-06-02 19:52 UTC, adityapb commented
I've made the changes @katyhuff

2017-06-02 21:26 UTC, katyhuff approved these changes
excellent.

2017-06-02 21:26 UTC, merged